services:
  app:
    depends_on:
      - db
    build: .
    environment:
      - DB_DOMAIN=db
    entrypoint: ./wait-for-it.sh db:${DB_PORT} --strict -- ./docker-entrypoint.sh

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
