"""Created Requisites model

Revision ID: 0efb6694ce08
Revises: 28dc76fdcbd7
Create Date: 2024-05-18 16:32:29.493773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efb6694ce08'
down_revision = '28dc76fdcbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisites',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('bic', sa.String(length=9), nullable=False),
    sa.Column('bank', sa.String(length=32), nullable=False),
    sa.Column('checking_account', sa.String(length=32), nullable=False),
    sa.Column('correspondent_account', sa.String(length=32), nullable=False),
    sa.Column('swift', sa.String(length=32), nullable=False),
    sa.Column('iban', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_index('ix_users_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_password', ['password'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    op.drop_table('requisites')
    # ### end Alembic commands ###
